### ISSUE TITLE
frozen_inference_graph.pb is missing

### ISSUE THREAD

**Issue by LitoNeo** [issaiass/jetbot_perception#2]
Hi issaiass, and the frozen_inference_graph.pb is missing too, may you share that? Thank you~

**Comment by issaiass** [comment]
We are using tensorflow, so you need to go to the models folder or download using wget

wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz
tar -zxf ssd_mobilenet_v2_coco_2018_03_29.tar.gz


https://github.com/issaiass/jetbot_perception_2d is the main repo, not this one
